### ISSUE TITLE
More than one enum within a file

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#160]
It's quite cumbersome that enum values from different enums classes can collide.
Did you consider changing that or support an option to switch this?
Why are the items not just moved inside the class?

**Comment by zoechi** [comment]
I guess a main reason for the current design is to require users to write as little code as possible and get the rest generated.
If the amount of manually written code doesn't matter (because it's auto-generated)
would would it need to make such enums work with built_value?

**Comment by davidmorgan** [comment]
The way this is supported is that you can make the right hand side of the enum constant anything you want:

```
  static const SecondTestEnum yes = _$ys;
  static const SecondTestEnum no = _$n;
  static const SecondTestEnum definitely = _$definitely;
```

So, yes, they can collide -- but you can just change the name to something else.

There isn't really a better way to do this, unfortunately, because static consts can't be inherited, redirected, anything other than assigned other static const values. It would be possible to generate nested classes:

```
  static const SecondEnumValue yes = _$SecondEnumValue.yes;
```

but that needs more typing and creates an extra class that doesn't really do anything. If you wanted you could name your constants like this anyway to avoid collisions:

```
  static const SecondEnumValue yes = _$secondEnumValueYes;
```

Hope that helps!

**Comment by zoechi** [comment]
I read the explanation in the source several times but it seems I wasn't able to fully understand it.
All is working fine now.
Thanks a lot for your patient support :)
