### ISSUE TITLE
Consider requiring @required on factory constructor

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#188]
It would unfortunately be a breaking change, but in my opinion it always makes sense to annotate named arguments in the factory constructor with @required, unless they are @nullable fields. If you don't pass them, the builder will throw at construction time. It might be nice if the generator protected you against forgetting the @required annotation.

**Comment by matanlurey** [comment]
How would this work if you have a builder with default values?

**Comment by joshua-i** [comment]
I guess I'm just talking about a forwarding factory constructor that points at the new generated constructor, using the pattern in the last code snipper of #6 here: https://medium.com/dartlang/moving-fast-with-dart-immutable-values-1e717925fafb

**Comment by davidmorgan** [comment]
Thanks Joshua!

I tried this, but it doesn't work: if I add `@required` on the generated constructor it has no effect when you forward to that constructor.

```
factory NamedFactoryValue({int value}) = _$NamedFactoryValue._;

... later ...

_$NamedFactoryValue._({@required this.value})
```

i.e. the analyzer doesn't care about the annotation on _$NamedFactoryValue, it's apparently only looking for `@required` on NamedFactoryValue.

Maybe open an issue against the analyzer or package:meta?

I'm not _too_ enthusiastic about this, though, because `@required` anyway doesn't help with the builder pattern. I have hopes that by supplying a built_value analyzer plugin we can do that required check for you.

Thanks!

**Comment by joshua-i** [comment]
Sure, definitely not a high priority, just a nit I noticed. I'll open a bug against meta (looks like it's just part of the sdk project?). It does make sense for a constructor to propagate that kind of information from the constructor impl it's using.

**Comment by davidmorgan** [comment]
Thanks!
