### ISSUE TITLE
Non-instantiable classes can't be attributes of a Built.

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#192]
The problem is with the generated Builder. If I have something like:
```
@BuiltValue(instantiable = false)
abstract class Base implements Built<Base, BaseBuilder> {
  String get foo;
}

abstract class HasBase impelments Built<HasBase, HasBaseBuilder {
  Base get base;
  // ... other methods, constructors, etc. 
}
```
Then the HasBaseBuilder tries to initialize its base variable to "new BaseBuilder()". Of course, since BaseBuilder is abstract, this fails. I'm not sure what the right solution is. A couple simple options:
- Just don't try to initialize in the Builder when it's non-instantiable. However, I think this would make it very easy for clients to get an NPE while trying set a nested value on it (e.g. `hasBaseBuilder.base.foo = "a"`)
- Make the variable in HasBaseBuilder a Base, instead of a BaseBuilder.

**Comment by dave26199** [comment]
Thanks. Looks like we should at least detect that the constructor doesn't exist -- and if not, not generate a call to it. Defaulting to Base instead of BaseBuilder makes sense.

Note that you can if you like write your own implementation of BaseBuilder. You'd have to make it so it knows about one or more of its concrete subclasses, and ends up instantiating one of those. Depending on how you're using it this may be the best way to go.

I'm currently on vacation so it'll be a couple of weeks before I can look at this.

**Comment by dave26199** [comment]
Actually, we should just give BaseBuilder a constructor, and make it non-abstract.

It can have just "replace" and "build" methods. That's enough for it to be usable.

Then we can look at ways to make it more interesting by hooking in build functionality for subclasses.

**Comment by dave26199** [comment]
You'd always have to call "replace", there would be no default instance.

joshua-i <notifications@github.com> schrieb am So., 16. Juli 2017, 14:33:

**Comment by davidmorgan** [comment]
I realize the simpler/neater fix here is to not try to use the abstract BaseBuilder at all. I'll do that.
