### ISSUE TITLE
DateTimeSerializer truncates microseconds

### ISSUE THREAD

**Issue by jt70** [google/built_value.dart#206]
The DateTimeSerializer drops the micro seconds when serialized/deserialized.  Obviously a minor issue, but you might expect that serializing/deserializing something would give the same result as the original value.  Maybe this is by design though?  

var date = new DateTime.now().toUtc();
print(serializers.deserialize(serializers.serialize(date)));
print(date);
print(date == serializers.deserialize(serializers.serialize(date)));

> 2017-08-10 03:59:29.575Z
2017-08-10 03:59:29.575328Z
false

**Comment by davidmorgan** [comment]
Thanks for filing!

It's serialized using millisecondsSinceEpoch rather than microsecondsSinceEpoch. IIRC this was accidental -- I'm used to thinking of time in millis, so that's what I used.

Fixing this would be a breaking change to serialization, which is unfortunate. We could provide an _option_ to switch to micro precision serialization ... if anybody needs it. At this point I'm tempted to wait for somebody who actually needs full precision. What do you think?

**Comment by jt70** [comment]
Yes, I was thinking the same thoughts.  I don't actually need it, it's just messing with my unit tests which I can hack around. I mostly just wanted to give you a heads up about it.

**Comment by jt70** [comment]
One more thought... If this ever revisited, it may be better for cross language/library support to use an ISO 8601 string, I'm not sure about this though.

**Comment by davidmorgan** [comment]
Thanks. I'll leave this open so I don't forget.

**Comment by davidmorgan** [comment]
Thought about this a bit more; I think it should be fixed as a matter of principle. (Serialize/deserialize returns the same value, as you said).

I have another breaking change to serialization in mind, so I'll do both and release as v3. (At some point).

Thanks again.
