### ISSUE TITLE
Add an annotation to indicate a field should be skipped for serialization

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#207]
Perhaps a custom serialization plugin would be able to do that as well, but without annotation support, it is cumbersome.

**Comment by davidmorgan** [comment]
Do you have an example where this is useful, please?

I guess the field needs to be @nullable? Or is it just left as the default when deserialized?

Thanks.

**Comment by zoechi** [comment]
My current use case is exceptions that contain information for the user and also information only for the developer or to be logged on the server (but not intended for the user).
Making it `@nullable` would be necessary and fine of course.  

I can also create a copy before serializing where I omit the internal information, but it seems inefficient and unnecessary and I think I saw this in other serialization solutions and was curious if this is already supported or consider adding it. 

Another idea was to support custom annotations in some way, so that its value can be used in a custom serialization plugin. Then I could use one serializer when sending the value to the client and omit some fields, and another serializer when I send it for example to a different server instance, where I actually might want to send all fields.

**Comment by davidmorgan** [comment]
Hmm. Doesn't that extra information also have a detrimental effect on operator==/hashCode? I guess you want to ignore it when comparing.

Here's an option you almost certainly haven't thought of: you can maintain two different versions of the class, one with the fields for the server, and one without for the client. They need to have the same name. Provided they have the same required fields, they're compatible for serialization.

This may be a particularly attractive option if the server and client use of the class usually need different code.

This is the "allows different object oriented models over the same data" feature from the README.md :)

I'm not aware of anyone doing this yet, but it's definitely supported. For it to work well there should be a tool which checks that the different versions of the classes are wire compatible -- I do expect to write one, but since nobody has needed it, I haven't started on that yet.

Of course, that may not work for you at all. One other thing I'd like to explore is whether there's a reasonable way to move the data out of the class; you could for example have a server-only class that wraps the client-only one, or you could move the data out into a global map.

Failing all that if there's still a good use case let's add the annotations :)

**Comment by zoechi** [comment]
You're right about `==`, they would need to be excluded. 
This seems to be too much fuzz for the gain. 
I rather not have different classes. I like being able to just share the model classes between client and server.
Perhaps I'll just stick with creating a new modified instance before sending it over the wire.

**Comment by zoechi** [comment]
Can I have a custom serializer implementation?

**Comment by davidmorgan** [comment]
I'm not sure I understand the question :)

**Comment by zoechi** [comment]
I meant if a built_value class has a field that is not one of the supported types, can I implement the serializer code myself, but I think a serializer plugin is the way to go.

**Comment by davidmorgan** [comment]
Yes, I think either should be possible -- implementing the serializer yourself, or using a serializer plugin.

Back in August you were rethinking whether you needed this -- I guess you're now thinking it would be a good idea, again? :)

**Comment by zoechi** [comment]
Yes, I run into that frequently. 
I use `built_redux` and when I persist the state, I don't want to persist certain properties.
I'm still not sure if it's worth the annotation.
An annotation would be easier for simple cases than a serializer prlugin.
