### ISSUE TITLE
Deprecating/renaming a BuiltValue class nearly impossible

### ISSUE THREAD

**Issue by matanlurey** [google/built_value.dart#257]
From https://github.com/dart-lang/code_builder/issues/154.

I'd like to `@Deprecate` a `Built<...>` class, and replace it with another.

I tried the following strategy:

```dart
@Deprecated('Replace with "Library" by 3.0.0')
abstract class File implements Built<File, FileBuilder>, Spec {
  factory File([void updates(FileBuilder b)]) = _$File;
  File._();

  BuiltList<Directive> get directives;
  BuiltList<Spec> get body;

  @override
  R accept<R>(
    SpecVisitor<R> visitor, [
    R context,
  ]) =>
      visitor.visitFile(this, context);
}

@Deprecated('Replace with "LibraryBuilder" by 3.0.0')
abstract class FileBuilder implements Builder<File, FileBuilder> {
  factory FileBuilder() = _$FileBuilder;
  FileBuilder._();

  ListBuilder<Directive> directives = new ListBuilder<Directive>();
  ListBuilder<Spec> body = new ListBuilder<Spec>();
}

@immutable
class Library extends _$File implements Spec {
  factory Library([void updates(LibraryBuilder b)]) {
    return (new LibraryBuilder.__()..update(updates)).build();
  }

  Library._({
    BuiltList<Directive> directives,
    BuiltList<Spec> body,
  })
      : super._(directives: directives, body: body);
}

// TODO: Remove File in 3.0.0.
// ignore: deprecated_member_use
class LibraryBuilder implements FileBuilder {
  // ???
}
```

... but I'm having a hell of a time getting Library/LibraryBuilder to work without breaking the public API. Any ideas here? Am I holding it wrong?

**Comment by davidmorgan** [comment]
Yeah, this is hard. Generally, you're not allowed to inherit from another built_value--this would break the contract of operator==.

You can "implement" another built_value; one of the two needs to be marked @BuiltValue(instantiable: false), as in this example:

```
https://github.com/google/built_value.dart/blob/master/example/lib/polymorphism.dart#L24
```

but the generator stops you from writing a factory in the class. (Because if you did ... it would be instantiable).

I think the best you can do right now is to drop the `Built` interface and write approximately the same thing by hand, with the `implements` clauses to make everything work.

Suggestions on how to improve this welcome :)

**Comment by davidmorgan** [comment]
I don't think there's a lot to improve here; suggestions welcome, but for now I'll close this. Thanks.
