### ISSUE TITLE
Const Set of values in EnumClass 

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#263]
I ran into a case where it would be nice to be able to get at the values of an EnumClass as a const. The generated symbol for the values getter is a BuiltSet, so that doesn't work. Could we get some way to (optionally?) get a regular const Set of the values?

Maybe this is too much of a tangent, but is it crazy to have a const implementation of BuiltSet? I imagine this has been previously considered, but it looks like the only reason it's not const is so that the _hashCode can be lazy and memoized.

**Comment by joshua-i** [comment]
Oh, duh, there's no way to get a const Set, so forget the consts BuiltSet idea, I guess.

**Comment by davidmorgan** [comment]
Yeah, the problem is _hashCode. This isn't just needed for hashing -- it also significantly speeds up operator== by quickly finding cases where lists/sets/maps are the same size but with different content. Since hashing and comparison are a big part of what the Built classes offer it's hard to see how to offer a const version.

What we _could_ potentially do would be to expose a const `List` of values. (The one we instantiate the `BuiltSet` from). Would that help?

**Comment by joshua-i** [comment]
Yes, a const List of values would work for me.
