### ISSUE TITLE
Check for dynamic T for built_value should be in value class

### ISSUE THREAD

**Issue by dave26199** [google/built_value.dart#337]
Currently we only check in the builder, which allows instantiation with `<dynamic>` via the value class.

**Comment by davidmorgan** [comment]
For Dart 2 it probably makes more sense to move the check altogether; Dart 2 is sound for types, no need to forbid `dynamic`.

**Comment by davidmorgan** [comment]
On second thoughts, I don't see a benefit to allowing `dynamic`; it's better to keep prohibiting it, and fix the check.

**Comment by ijann** [comment]
Hello, I have a problem with a data type,
Color, a variable of type Color, I can not generate the serializable file, because this is dynamic, you could help me solve this problem.
If I had to create a color data type, how can I do it?

**Comment by ijann** [comment]
Well, I answer to myself, I already solve it,
copy the color class of the dart core with its constructors
and methods,
only the code that defines the type of color data,
So it worked for me, simple,
I avoided creating a color data type
if I have the source code of the Color class.
built_value asked me to define a data type.
Something you do not do when you use the Color class of dart,
since you do not care about that class,
if you do not care about it then,
you have to paste the code inside the class.
The necessary code to define the type of data. ;)
