### ISSUE TITLE
Allow types to specify a custom serializer

### ISSUE THREAD

**Issue by sroddy** [google/built_value.dart#353]
Hi,
reading the docs I see that built_value allows only other built_values/built_collections to be included within a built_value tree.
However I have some cases where, in order to provide a simpler API to end users, I would like to put inside a serializable built class (and possibily built collection) instances of well-behaved types that have manual equatable and hashable implementations, together with a serializer.

Is it possible to do so? How?

**Comment by davidmorgan** [comment]
Yes, this is possible.

If you want the resulting type to be serializable then you need to provide your own serializer for your custom types. Take a look at the existing serializers (in built_value/lib/src) and see if they make sense--they're pretty straightforward. Happy to answer questions there.

In general classes that are immutable, comparable and hashable interoperate well with `built_value` and `built_collection`. For `built_value`, you can mark fields as `@BuiltValueField(comparable: false)` to stop them being used for `operator==` and `hashCode` if they are not well behaved. You can also mark fields `@BuiltValueField(serializable: false)` to exclude them from serialization. If you do this they must also be marked `@nullable`.

**Comment by sroddy** [comment]
Is there a way to provide a custom serializer inside a class (the `static Serializer<TYPE> get serializer => _$typeSerializer`) without triggering errors in the code generation? I would like to avoid having to add them by hand in the app serializers, especially if they are needed by a indirect dependency

**Comment by davidmorgan** [comment]
That sounds reasonable. I'd still like the default workflow to guide people to the current version, though.

We could add an annotation:

```
@BuiltValueSerializer(custom: true)
static Serializer<TYPE> get serializer => <whatever you want>
```

or use a different field name

```
static Serializer<TYPE> get customSerializer => <whatever you want>
```

or require a specific form for the RHS

```
static Serializer<TYPE> get serializer => new TYPESerializer();
```

or require that you have the same RHS and implement it yourself:

```
static Serializer<TYPE> get serializer => _$typeSerializer;
static Serializer<TYPE> get _$typeSerializer => <whatever you want>
```

...any thoughts? My main concern is that if people typo the `_$typeSerializer` part that they get a build failure pointing them to the correct version.

**Comment by sroddy** [comment]
I think that writing `static Serializer<TYPE> get serializer => new ANYTHING();` would be different enough not to be typo'ed with `static Serializer<TYPE> get serializer => _$typeSerializer;`

But `@BuiltValueSerializer(custom: true)` looks like the best approach to me.

**Comment by ordsen** [comment]
I would also benefit from this. In my use case a 'per field' (de)serializer would be helpful. 

E.g. I have a class with several fields which the built value serializer handles pretty well and one field which it doesn't. It would be nice to be able to point the (de)serializer to a custom function declared by my class and instead of calling `serializers.deserialize(fieldWhichIWantToCustomDeserialize, specifiedType: const FullType(TheFieldsType) as TheFieldsType )` during serialization the deserializer would call something like `specifiedCustomDeserializer(fieldWhichIWantToCustomDeserialize )`. I think this can be added to this topic. 
Anyway, I see that it might become inconvenient to specify all custom serializers/deserializers this way if you need a lot of them.

Regarding my use case: I have a 64bit int in my database and JS on my backend which returns it as a String to my App (due to its 53bit limitation). I would use this functionality to specify the conversion from String to int as Dart supports 64bit ints.. Or do you see a simpler solution instead of using custom (de)serializers?

**Comment by davidmorgan** [comment]
For that specific use case, declaring the field as an `Int64` might do what you want. It's serialized as a string. Or did you want to avoid using the actual `Int64` type?

**Comment by ordsen** [comment]
I just had a look at the `int64_serializer` but it looks like it can only handle Strings. I would like to be able to deserialize both ints and Strings to 'usual' ints, the deserializer should handle the passed value properly - independent of the actual type. 
That way I can add a _primary key_ property through inheritance to all classes which are synchronized with my data base; the deserialization handles all details of the received server response so that my other code can access the _primary key_ property as a plain dart `int` (and doesn't need to consider 64bit ints vs 32bit ints).

**Comment by davidmorgan** [comment]
I see. What behaviour do you want when you serialize again--I guess, use an int if it fits in a javascript double, otherwise use a string?

I guess you could make the `int` serializer do that, then it would work for any `int` field. i.e. replace the default `int` serializer with your own.

**Comment by ordsen** [comment]
Yes exactly; I didn't see that but it sounds like a good solution. 
Currently I just copy pasted the generated code for that class to my original ("not-generated") file, tweaked the deserialization and pointed the `static Serializer<TheClassIMentioned> get serializer` to that custom serializer, but that stopped working in the latest release. I think I'll implement your solution, thanks!

**Comment by davidmorgan** [comment]
No ETA I'm afraid, but I'll try to fit it in with the next round of changes if I can.
