### ISSUE TITLE
Migrate away from computeNode

### ISSUE THREAD

**Issue by natebosch** [google/built_value.dart#358]
`computeNode` moves you from the element model to the AST model. This is more expensive and will eventually be removed - especially if we migrate build away from the analyzer onto front_end.

We expect most builders should be able to operate on the element model and we can work together on any specific issues that come up.

This is not urgent - filing so it's on your radar.

**Comment by davidmorgan** [comment]
Thanks Nate. As it happens I chatted with the analyzer team in detail about this last week.

built_value will have to continue to use the AST model--it does a few things that will never be supported in the element model, including 1) getting the name of unresolved types and 2) checking the exact form of a constructor or getter.

What was suggested is that it should be possible to use the AST without using `computeNode`. Instead the AST should be computed once and `NodeLocator2` should be used to find the desired AST node within this as needed.

I think this means a feature request to `build` and `source_gen` to provide that AST model so that generators don't have to call `computeNode` to get it. Let's discuss. @jakemac53

**Comment by jakemac53** [comment]
Ok, we should also figure out long term how this will work with the move to the common frontend.

**Comment by matanlurey** [comment]
(And Kernel/Summary files)

**Comment by davidmorgan** [comment]
This is now done.
