### ISSUE TITLE
add generated factory constructor for for less typing

### ISSUE THREAD

**Issue by ride4sun** [google/built_value.dart#375]
Not sure if that is possible to generate but could you add factory constructors  in the generated code to save some typing?  E.g.

```
  
  factory LoginInfo.init(String userName, String password, String cloudId) =>
      new LoginInfo((b) => b
        ..userName = userName
        ..password = password
        ..cloudId = cloudId);
```
here are the number of lines compared.

```
     final loginInfo = LoginInfo.init(_email, _password, _cloudId);

    final loginInfo = (new eagle.LoginInfoBuilder()
          ..userName = _email
          ..password = _password
          ..cloudId = _cloudId)
        .build();
```

**Variations**

```
 
  factory LoginInfo.initAll({@required String userName, @required String password, @required String cloudId}) =>
      new LoginInfo((b) => b
        ..userName = userName
        ..password = password
        ..cloudId = cloudId);

  final loginInfo = LoginInfo
        .initAll(userName: _email, password: _password, cloudId: _cloudId);


  factory LoginInfo.initSome({String userName, String password, String cloudId}) =>
      new LoginInfo((b) => b
        ..userName = userName
        ..password = password
        ..cloudId = cloudId);

   final loginInfo =
           LoginInfo.initSome(userName: _email, password: _password);

```

**Comment by davidmorgan** [comment]
There actually is such a factory constructor--it's called "_".

Because it's private, you'll have to add a public constructor that forwards to it, like this:

```
factory LoginInfo.init(String userName, String password, String cloudId) = _$LoginInfo._;
```

This is allowed to be the main constructor if you like:

```
factory LoginInfo(String userName, String password, String cloudId) = _$LoginInfo._;
```

You can also use it to provide other convenience constructors. For example, for a single field class I often do:

```
factory SimpleClass(String value) => new _$SimpleClass._(value: value);
```

**Comment by ride4sun** [comment]
Thx for the answer.
Is there a easy way that I can extend the generated code that I can add the three c-tors mentioned above for all my classes ?

**Comment by davidmorgan** [comment]
There's no way to generate factories for you, unfortunately. The best that's possible is that you add the factories yourself and delegate to either the generated no-name constructor or the generated `_` constructor.

This is because the factories have to be in the class you define, there's no way to use them from elsewhere.

**Comment by ride4sun** [comment]
Thx for the info. I am still learning the details of dart.

**Comment by davidmorgan** [comment]
I'll close this, please re-open if you need more help / if there's a feature request. Thanks!

**Comment by atsu85** [comment]
@davidmorgan, thanks for the reply :)
In the first comment you gave an example:
> Because it's private, you'll have to add a public constructor that forwards to it, like this:
> 
> ```
> factory LoginInfo.init(String userName, String password, String cloudId) = _$LoginInfo._;
> ```
but i can't get it to compile. Not sure, if the problem was in your example, in my class implementation or version of some dependency or even Dart itself (i use Dart version 2), but following code:
```Dart
library log_info;
import 'package:built_value/built_value.dart';
part 'log_info.g.dart';

abstract class LoginInfo implements Built<LoginInfo, LoginInfoBuilder> {
  String get userName;
  String get password;
  String get cloudId;

  LoginInfo._();

  factory LoginInfo.init(String userName, String password, String cloudId) = _$LoginInfo._;
  // ------------------------------------------------------------------------^^^^^^^^^^^^^
  // error: The redirected constructor '({userName: String, password: String, cloudId: String}) → _$LoginInfo'
  // has incompatible parameters with '(String, String, String) → LoginInfo'. 

  factory LoginInfo([updates(LoginInfoBuilder b)]) = _$LoginInfo;
}
```
produced compile-time error (see the comment bellow factory constructor).
However if i replace factory constructor with smth like:
```Dart
//factory LoginInfo.init(String userName, String password, String cloudId) = _$LoginInfo._;
  factory LoginInfo.init(String userName, String password, String cloudId) => _$LoginInfo._(
    userName: userName,
    password: password,
    cloudId: cloudId,
  );
```
then it compiles just fine.
Any ideas, if i'm doint smth wrong, or was the sample incorrect?
