### ISSUE TITLE
Question about calculated defaults

### ISSUE THREAD

**Issue by ArneSaknussemm89** [google/built_value.dart#385]
Part of this is probably because I'm still learning Dart, but I hit a small wall that I can't figure out.

Let's say I have this abstract class as my base:
```dart
@BuiltValue (instantiable: false)
abstract class CharacterClass extends Object with Character {
  CharacterClass rebuild(void updates(CharacterClassBuilder b));
  CharacterClassBuilder toBuilder();
}

abstract class Character {
  String get name;
  int get level;

  @nullable
  int get health;
}
```

And now let's say I extend it onto a new class:
```dart
abstract class AwesomeClass extends Object implements CharacterClass, Built<AwesomeClass, AwesomeClassBuilder> {
  static Serializer<AwesomeClass> get serializer => $_awesomeClassSerializer;
  int healthModifier = 5;
  
  factory AwesomeClass([updates(AwesomeClassBuilder b)]) = _$AwesomeClass;
  Awesome._();
}
```

What I'm wanting to do is calculate the initial health based on what level the character is (if health is not passed to the builder). So if I do:
```dart
  final character = new AwesomeClass((b) => b
    ..name = "Awesome Guy"
    ..level = 3);
```
.. how can I add a way to do something like:
```dart
abstract class AwesomeClassBuilder implements Builder<AwesomeClass, AwesomeClassBuilder> {
  @virtual
  int health = this.level * this.healthModifier;

  factory AwesomeClassBuilder() = _$AwesomeClassBuilder;
  AwesomeClassBuilder._();
}
```

Values from `AwesomeClass` are not usable while inside the builder. How can I access the built classes values inside the builder? Or am I just doing this *completely* wrong?

**Comment by dave26199** [comment]
This is an area that could use some improvement; there's an issue open here with quite a bit of discussion:

https://github.com/google/built_value.dart/issues/212

I think the track you're on is a good one, but doesn't actually work right now. If you added the other fields from `AwesomeClass` to `AwesomeClassBuilder`, i.e. `String name`, `int level`, `int health`, then you'd be able to access them. But you still wouldn't be able to use those for the defaults, because setting them inline is too early, and I don't think there's currently a way to hook into the `build` method.

The way that I think does work is to customize the factory for `AwesomeClass`. Something like:

```
factory AwesomeClass([updates(AwesomeClassBuilder b)]) => {
  var result = new _$AwesomeClassBuilder()..update(updates);
  if (result.health == null) {
    result.health = result.level * result.healthModifier;
  }
  return result.build();
}
```

Please let me know if this works for you.

The main downside is that the default will not apply if you create an instance by explicitly creating a builder; it only applies via this factory.

This is definitely something I'd like to improve.

**Comment by ArneSaknussemm89** [comment]
Further messing with this bring me to an interesting point: If I have a field that needs to calculated from other values; it should be memoized. After thinking about it a bit, it made more sense.

So I think using a custom builder and setting default values in that makes the most sense. That way whether instantiated with the factory or created from the builder you would still get the defaults.

I think for default static values I'll just stick to the builder pattern, and if I need to calculate values, then memoized values is the way to go.

**Comment by davidmorgan** [comment]
I'll close this in favour of #212. Thanks.
