### ISSUE TITLE
Nested objects holding reference to parrent

### ISSUE THREAD

**Issue by neckaros** [google/built_value.dart#402]
Hello,

Is there a good approach to build a nested collection while keeping a reference to parent (to build paths) using built_values?
```
abstract class Tag implements Built<Tag, TagBuilder> {
  static Serializer<Tag> get serializer => _$tagSerializer;
  String get id;
  String get name;
  @nullable
  Tag get parent;
  BuiltList<Tag> get children;

  String get path => '${parent.path ?? ''}/$name';

  factory Tag([updates(TagBuilder b)]) = _$Tag;
  Tag._();
}
```
(this won't work has parent expect a builder and not a refenrece
Or is it not appropriate to this need? (for exemple here parent accept a builder and not a refenrece; holding a reference to a parent can be problematic for serialization/deserialization...)

**Comment by dave26199** [comment]
Right, `built_value` does not support references to parent, because it causes problems for serialization, equality, hashing ... pretty much everything :)

One possibility would be to store the link to parent with IDs rather than references, i.e. to give each tag an integer ID and store them in a `Map<int, Tag>`.

**Comment by neckaros** [comment]
Indeed reference complicated everything :)
yes i think your option should be the best. Thanks for your **very** quick advice 😄

**Comment by davidmorgan** [comment]
I'll close this for now; please re-open if you need more help / would like to suggest a feature. Thanks!
