### ISSUE TITLE
Let me define a constructor

### ISSUE THREAD

**Issue by kevmoo** [google/built_value.dart#41]
Sometimes you just want a constructor to take in args. Building for two String properties is crazy heavy.

**Comment by davidmorgan** [comment]
It'll need to be a factory rather than a constructor so the generated type can be used. The canonical way of doing what you suggest is:

factory Foo.of(String fieldOne, String fieldTwo) =>
    new Foo((b) => b
      ..fieldOne = fieldOne
      ..fieldTwo = fieldTwo);

And indeed we see this pattern a lot where there is a small fixed number of fields.

If you're worried about performance, you _could_ reference the internal constructor, but I don't want to encourage this:

factory Foo.of(String fieldOne, String fieldTwo) =>
    new _$Foo._(
      fieldOne: fieldOne
      fieldTwo: fieldTwo);

Instead I'll look at optimizing the cost of the builder-based version. It should be possible to get it pretty close to the direct-constructor version, and then that'll help all the other uses of built_value too.

**Comment by davidmorgan** [comment]
@kevmoo I looked at the performance a little; it's true that the direct version is faster, but both are so far -- tens or hundreds of millions of instantiations per second -- that I don't think it's likely to make a difference in practice.

So I'd like to wait for a use case before optimizing.

Apart from that, does the factory example I gave do what you want?

**Comment by kevmoo** [comment]
For "Heavy", I wasn't talking about perf. I was talking about usability. It's a crazy amount of typing to create a class w/ two trivial fields.

**Comment by davidmorgan** [comment]
Makes sense. Then, you can add a factory constructor as suggested above -- we often do this. Please let me know if there's anything missing.
