### ISSUE TITLE
How to: using build_value in package

### ISSUE THREAD

**Issue by tdesc** [google/built_value.dart#415]
My target is to move build_value generated classes to isolate package and use it both in AngularDart and Flutter projects.
how to use part "" and generated Builder ( like AppStateBuilder ) in separate project.

**Comment by davidmorgan** [comment]
Sure, you can do that.

Put your built_value classes in a new folder with its own `pubspec.yaml`, `lib` subdirectory, etc; in `pubspec.yaml` give it a different project name e.g. `my_built_value_classes`.

Then in your other package(s), add a dependency to `pubspec.yaml` on `my_built_value_classes`. Instead of specifying a version, you'll probably want to use a path for local development, e.g.

```
  my_build_value_classes:
    path: ../my_built_value_classes
```

If/when you want to publish the package(s), you'll need to change this to a real dependency; if you don't publish them (the package is private) then it can stay as a path dependency.

I hope that helps :)
