### ISSUE TITLE
Proper step by step documentation related to usage

### ISSUE THREAD

**Issue by techyrajeev** [google/built_value.dart#469]
I am quite new to flutter and dart and tried to integrate `built_value` along with other built packages to auto generate data models being used in the project but couldn't figure out steps to do it.
Even official flutter.io documentation does not mention descriptive guide-lines for the same.

I watched the [video](https://www.youtube.com/watch?v=TMeJxWltoVo) and it looked quite promising to me. So I decided to use it my flutter project. 
Please improve the documentation little bit so that it becomes quite easy to integrate with flutter.

**Comment by davidmorgan** [comment]
Unfortunately I don't use flutter--I'd like to--so I haven't been able to add detailed instructions. One way to do it is to make a separate non-flutter Dart package with your built_value types; then it's exactly like the non-flutter case. Otherwise, you have to go through the flutter tools to do the build.

**Comment by techyrajeev** [comment]
I have been able to generate models for my flutter project although it wasn't easy for few days but I have figured out the way. I used flutter tools Its smooth now.
