### ISSUE TITLE
Serialized output missing quotationmarks

### ISSUE THREAD

**Issue by thomasnilsson** [google/built_value.dart#470]
Whenever I serialize a Dart object it is missing quotationmarks/apostrophes around both keys and values.

Am I missing something?

Thanks for the much needed library by the way!

**Comment by zoechi** [comment]
That's usually only when you just call `toString()`. 
Serialized output always contains quotes, otherwise it would not be valid JSON.
Perhaps you are missing

```
import 'dart:convert';
...
var result = jsonEncode(serializedData);
print(result);
```
because the serialized result is just lists and maps and primitive values, which does not contain quotes in the `toString()` result.
To get a JSON string, you need to make that extra step above.

**Comment by thomasnilsson** [comment]
Thanks, that is the way to do it 👍

**Comment by davidmorgan** [comment]
Thanks Thomas, thanks Guenter :)
