### ISSUE TITLE
BuiltList builder factory not being generated unless I add a dummy BuiltLIst to my class

### ISSUE THREAD

**Issue by biancashouse** [google/built_value.dart#522]
https://github.com/google/built_value.dart/issues/404 already identified this issue and was closed, but it is still a bug in the built_value generation process...

I have a built_value that contains a BuiltMap of BuiltList<SomeClass>.
i.e.   BuiltMap<String, BuiltList<MyClass>> get someLists;

The following should be generated in my serializers.g.dart:

...
      ..addBuilderFactory(
          const FullType(BuiltMap, const [
            const FullType(String),
            const FullType(BuiltList, const [const FullType(MyClass)])
          ]),
          () => new MapBuilder<String, BuiltList<MyClass>>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(MyClass)]),
          () => new ListBuilder<MyClass>()))
...

but the 2nd addBuilderFactory stmt only get generated if I declared a dummy BuiltList field, i.e. 

@nullable
  BuiltList<MyClass> get dummyList;

(I happen to use a BuiltList<MyClass> in another built_value class. So I need the 2nd factory to be generated for me).

**Comment by davidmorgan** [comment]
Rather than using a dummy field you can add the builder factory yourself, as per the example here:

https://github.com/google/built_value.dart/issues/404#issuecomment-384260600

This is unfortunately still a known issue. The plan is to some day figure out how to do this for you automatically, please follow this issue:

https://github.com/google/built_value.dart/issues/124

**Comment by biancashouse** [comment]
Many thanks for the clarification.
I'm developing a flowcharting app, so I have a potentially very deeply
nested model - I'm very grateful for built_value, built_collection, and
built_map. Cheers..
