### ISSUE TITLE
Improve checking for invalid Builders

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#536]
It would be nice to have a way to know all the problems that would cause a Builder to throw when build() is called. Right now, there's no way to get that because build() falls immediately on the first erorr. It seems like the most straightforward ways to fix this would be to either a) add a new method like canBuild() that returns some object describing the issues b) collect all the inside of build() and throw them all together in some Error that can contain them all. Personally, I prefer (b), even if it is technically a breaking change, since I suspect that in practice there are very few references to the specific Error classes that exist today. I imagine something like:

```dart
class BuiltValueError extends Error {
  final String type;
  final Set<String> nullFields;
  final Set<String> missingGenerics;
  final Map<String, BuiltValueError> nestedFieldErrors;
}
```

Does this make sense?

**Comment by davidmorgan** [comment]
This is the same idea as

https://github.com/google/built_value.dart/issues/319

But, I'm a bit worried about the amount of code. Currently the generated code looks like this:

```
try {
        _$failedField = 'simpleValue';
        simpleValue.build();
        _$failedField = 'validatedValue';
        _validatedValue?.build();
      } catch (e) {
        throw new BuiltValueNestedFieldError(
            'CompoundValue', _$failedField, e.toString());
      }
```

To catch all the errors we'd need a `try`/`catch` for every field instead of one `try`/`catch` for the whole class.

Unfortunately there's no way to have a full `canBuild` method without actually trying to build, because validation is done in the value class, not in the builder. It would only be able to report on nullability/generics.

I do think there's room for improvement here, but I'm not exactly sure what the best path is.
