### ISSUE TITLE
Simple example to convert a ISO 8601 string representing a timestamp to a DateTime object for a flutter app?

### ISSUE THREAD

**Issue by mrgithub** [google/built_value.dart#537]
I have a json with a string representing a ISO 8601 datetime.  How do I convert/deserialize this into a valid datetime object?

Any chance of an example please?

**Comment by davidmorgan** [comment]
You need to add `Iso8601DateTimeSerializer` to your `serializers`, as is done in this test:

https://github.com/google/built_value.dart/blob/master/built_value/test/iso_8601_date_time_serializer_test.dart

Then it expects all `DateTime` classes to be serialized using ISO 8601 instead of time since epoch.
