### ISSUE TITLE
How to deserialise top-level list of items

### ISSUE THREAD

**Issue by votruk** [google/built_value.dart#565]
For example I have json file:

```json
[
  {
    "name": "test1",
    "result": "success"
  },
  {
    "name": "test2",
    "result": "fail"
  }
]
```

How can I deserialise it properly?

I understand that possible way to do it is to wrap this list into top-level object with a key. Something like that:
```json
{
  "list_of_items": [
    {
      "name": "test1",
      "result": "success"
    },
    ...
  ]
}
```

But I have multiple files with such structure so I wonder if there any other ways to handle it?

**Comment by davidmorgan** [comment]
You could iterate over the top level list calling `serializers.deserialize` on each inner map. You'll need to use `StandardJsonPlugin` to get it to accept the map format instead of the default list format; the third heading here:

https://medium.com/dartlang/moving-fast-with-dart-immutable-values-1e717925fafb

**Comment by aasyria** [comment]
thanks

**Comment by anqit** [comment]
I have two issues with the above code snippet:
1) First I get the error `A value of type 'T?' can't be returned from the function 'deserialize' because it has a return type of 'T'`. I can fix this by adding  `!` :
```dart
T deserialize<T>(dynamic value) =>
    standardSerializers.deserializeWith<T>(standardSerializers.serializerForType(T), value)!;
//                                                                     add null check here ^
```
2) After that "fix" (Intellij now has a warning about that null check), I get the following error with I haven't been able to figure out:
```dart
T deserialize<T>(dynamic value) =>
    standardSerializers.deserializeWith<T>(standardSerializers.serializerForType(T), value)!;
//                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// `The argument type 'Serializer<dynamic>?' can't be assigned to the parameter type 'Serializer<T>'`
```

Any thoughts? My guess is later versions of Dart have more stringent type/null checking? Other ways to de/serialize collections of built values?
