### ISSUE TITLE
Question: How to deserialize a Json that can be String or Bool?

### ISSUE THREAD

**Issue by alexjuniodev** [google/built_value.dart#593]
I'm getting a Json that returns a image_url when it exists but it returns false when it's empty. How can I deserialize that? It's not possible using dynamic.

**Comment by davidmorgan** [comment]
It should work to use `Object`.

**Comment by alexjuniodev** [comment]
Getting this error now:

failed due to: Deserializing '[DN, 3N, SN]' to 'BuiltList<Object>' failed due to: Bad state: No serializer for 'Object'.

**Comment by davidmorgan** [comment]
Hmm, for that last error, you need to import `package:built_value/json_object.dart` in your `serializers.dart`.

**Comment by jack-r-warren** [comment]
I assume the original asker has found a solution one way or another, but I faced a similar issue (a JSON schema where a boolean field was allowed to hold "true"/"false" and 0/1 in addition to true/false, among other union-type fields). I figure others might come to this issue chasing the same problem in their own code.

My solution was to write my own `SerializerPlugin`, placed before [`StandardSerializerPlugin`](https://pub.dev/documentation/built_value/latest/standard_json_plugin/StandardJsonPlugin-class.html) in setting up the `serializers`. Since the schema I was using is object-based, the object received by the `beforeDeserialize` method is usually a map, so the plugin can use the keys to identify values to manipulate.

It is certainly a bit of a hack, but implementing my own serializer like suggested [here](https://medium.com/flutter-community/creating-custom-built-value-serializers-with-builtvalueserializer-46a52c75d4c5) would've been very unwieldy (the schema I'm working from has a ton of fields and just a few tricky union ones). A side effect of this approach is that values are transformed (if I read `"true"` in, the output would have `true`), but that's fine in my case, especially since now the class's field is a normal `bool` type.
