### ISSUE TITLE
Serializers class is only generated if Serializers type is specified

### ISSUE THREAD

**Issue by alanrussian** [google/built_value.dart#635]
```dart
// Does not build the serializers class and doesn't provide any warning.
@SerializersFor(const [
  Foo,
])
final _serializers = _$_serializers;

// Does build the serializer class.
@SerializersFor(const [
  Foo,
])
final Serializers _serializers = _$_serializers;
```

It took me awhile to figure out why it wasn't working. If the code generator is going to be that picky, it would be nice if it at least gave me an error on the first example there, which it could know to do given the annotation.

**Comment by davidmorgan** [comment]
Yes, sorry about that; I've been bitten by it too, but haven't actually gotten around to fixing it

https://github.com/google/built_value.dart/issues/313

I'll close that issue in favour of this one so it's nearer the top of the list :)

**Comment by dave-doty** [comment]
I vote that all built classes are automatically made serializable (e.g., by adding a `toJson` method), and annotation/code is only required to customize it. That seems as though it could actually be easier to implement. (Just like `==` and `hashCode` are always provided, although I haven't figured out an easy way to customize those.)

**Comment by davidmorgan** [comment]
`toJson` isn't sufficient; you also need a way to convert from JSON. This needs something static. Now that we have extension methods we _could_ add that in the generated code ... previously we needed a static declaration from you, which is why it is how it is today.

But, we don't want to always generate a serializer; lots of people use `built_value` without using serialization. One option would be to let you add an annotation to mark something serializable, rather than the serializer declaration; then we use extension methods to add the serializer declaration for you.

**Comment by dave-doty** [comment]
> But, we don't want to always generate a serializer; lots of people use built_value without using serialization.

Actually, can you help me understand this? Won't this be analogous to unconditionally generating `hashCode` and `==`, even though some people use built_value without storing the values in containers or otherwise testing for equality? Is there some overhead to having a generated serializer? Since it's static I assume it doesn't add memory overhead to every built_value object.

**Comment by davidmorgan** [comment]
The generated serializer is a lot more code than equals+hashCode :) and even if it can be tree shaken away, it has to be compiled, which costs something.

Also, you need to add the serializers import before we can generate it, or it won't even compile :D

**Comment by nickmeinhold** [comment]
> One option would be to let you add an annotation to mark something serializable, rather than the serializer declaration; then we use extension methods to add the serializer declaration for you. 

I think this would be really helpful - If I'm understanding, I could then add the annotation to my snippets and no longer need the extra step of adding each new class to the serializers list.  

Is this is in the works?  Would it be worth creating an issue with a request to add the annotation you describe?  

Thanks for the great work, built_value is super helpful!

**Comment by davidmorgan** [comment]
Extensions can't add static fields, so that doesn't work, I'm afraid.
