### ISSUE TITLE
Double quotes not supported

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#655]
When attempting to use double quotes for `part` declarations like this:

```dart
part "state.g.dart";
```

One gets messages to the effect of:

```
[SEVERE] built_value_generator:built_value on lib/state.dart:
Error in BuiltValueGenerator for abstract class ValidationState<TValue, TError> implements Built<ValidationState<TValue, TError>, dynamic>.
Please make the following changes to use BuiltValue:

1. Import generated part: part 'state.g.dart';
```

This makes the choice of double quotes and the enforcement thereof via the `prefer_double_quotes` linter impractical with `built_value`.

**Comment by davidmorgan** [comment]
It's easy enough to allow double quotes; I expect we will keep single quotes as the "recommended" way, though, just because it's confusing to offer two possibilities when suggesting fixes.

I'll take a look.

Please note that while there is no guideline about single vs double quotes in dart style, what we see in the wild is a strong preference for single quotes; <10% use of double quotes for imports. Do with this information what you will :)
