### ISSUE TITLE
Generator has problems with extension methods

### ISSUE THREAD

**Issue by dalewking** [google/built_value.dart#761]
Been playing with the new extension methods introduced in Dart 2.6 and the built_value_generator does not work if you declare an extension on the type for any of the properties in a built value. For example:

```
extension IntExtension on int {
  int get doubled => this * 2;
}

abstract class Foo implements Built<Foo, FooBuilder> {
  int get value;

  Foo._();

  factory Foo([void Function(FooBuilder) updates]) = _$Foo;
}
```

This fails the generator with the error:

> Error in BuiltValueGenerator for abstract class Foo implements Built<Foo, dynamic>.
> Please make the following changes to use BuiltValue:
>
> 1. Make field value have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.

If you remove the extension it succeeds.

**Comment by natebosch** [comment]
Similar problem in json_serializable: https://github.com/dart-lang/json_serializable/issues/564

I notice that we aren't using the latest analyzer, which is `0.39.1`.

https://github.com/google/built_value.dart/blob/71742e9ae5abb12cf10c1601c7d1f92998aff213/built_value_generator/pubspec.yaml#L14

I wonder if that is the problem.

@scheglov - should we expect that with older versions of the analyzer, introducing an extension can cause some types to show up as `dynamic`?

**Comment by scheglov** [comment]
Support for extensions was not complete until we switched to summary2, which was in https://dart-review.googlesource.com/c/sdk/+/115440

Actually, when I hack `chat_example` and add a new file with the code from the initial message, `pub run build_runner build` crashes with an internal error in analyzer.
```
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
package:analyzer/src/summary/link.dart 5568:5                     TypeProviderForLink._buildInterfaceType
package:analyzer/src/summary/link.dart 5533:23                    TypeProviderForLink.objectType
package:analyzer/src/summary/link.dart 926:67                     ClassElementForLink_Class._computeInterfaceType
package:analyzer/src/summary/link.dart 824:27                     ClassElementForLink_Class.supertype
package:analyzer/src/task/strong_mode.dart 303:33                 InstanceMemberInferrer._inferClass
package:analyzer/src/task/strong_mode.dart 335:9                  InstanceMemberInferrer._inferClasses
package:analyzer/src/task/strong_mode.dart 56:5                   InstanceMemberInferrer.inferCompilationUnit
package:analyzer/src/summary/link.dart 1640:7                     CompilationUnitElementInBuildUnit.link
```

It seems that when I run `pub get` in `chat_example`, I get `analyzer 0.37.1+1 (was 0.39.1 from path /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer) (0.39.1 available)`, which is summary1 based, and extensions are not yet fully done there.

With dependency override to use the bleeding edge `analyzer`, code generation completes successfully.

It is hard to me answer the exact question why something becomes `dynamic`, because I don't know which types code generations look for.

**Comment by natebosch** [comment]
@davidmorgan - I think this can be resolved by upgrading to the latest analyzer.

**Comment by dalewking** [comment]
I was able to get it to work using these dependency overrides (both were necessary):

```
dependency_overrides:
  analyzer: ^0.39.1
  build_resolvers: ^1.3.0
```

**Comment by davidmorgan** [comment]
Thanks everyone--looks like I need to bump the analyzer version everywhere. I'll try to get to that next week.

**Comment by davidmorgan** [comment]
We'll need a version bump to `analyzer_plugin` first. I'll ping them.
