### ISSUE TITLE
Question: Automatic / Dynamic field assignment on rebuild

### ISSUE THREAD

**Issue by elliottmb** [google/built_value.dart#763]
I've been investigating switching to built_value for our data models, but one area has me hung up. I would like to be able to set a `hasChanges` like field when a model is rebuilt with new values. We're currently doing something like this to minimize useless writes.

In our current models, we'd been following the common pattern of `copyWith()` and setting it there.

For example

```
  SomeModel copyWith({
    String someField,
    String someOtherField,
    bool deleted,
  }) {
    bool hasChanges = false;
    if ((someField != null && someField != this.someField) ||
        (someOtherField != null && someOtherField != this.someOtherField) ||
        (deleted != null && deleted != this.deleted)) {
      hasChanges = true;
    }

    return SomeModel(
      id: this.id,
      someField: someField ?? this.someField,
      someOtherField: someOtherField ?? this.someOtherField,
      hasChanges: hasChanges || this.hasChanges,
      deleted: deleted ?? this.deleted,
    );
  }
```

Is it possible to accomplish the same thing in the builder pattern?

Essentially a hydrated model and a new model would have `hasChanges = false`, but the moment a field is adjusted it has `hasChanges = true` for the rest of its lifetime.

**Comment by davidmorgan** [comment]
Hmm, that's a fun problem :)

We don't currently track enough information inside the builder to do that.

We could, in every setter, check the value you're setting against the current value before you set it. That would make changes more expensive, but would allow us to return the _identical_ instance if nothing changed, instead of an equal copy.

Would that allow you to minimize useless writes? If you keep the old instances around you could use `identical(old, new)`, which is very cheap, to see if they changed.

I can't think of a nice way to support the `hashChanges` field directly. Open to suggestions :)
