### ISSUE TITLE
Publish built_value_analyzer_plugin

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#779]
Waiting on a release of the analyzer_plugin package.

**Comment by simolus3** [comment]
Is this blocked because `analyzer_plugin` doesn't support `analyzer >=0.39` yet? Just curious because I'm also desperately waiting for such version.
I made a PR to support that version in `analyzer_plugin` which recently got merged, but I couldn't reach anyone to actually publish that. If you're waiting as well, I assume you have better luck reaching someone?
