### ISSUE TITLE
You should add must_be_immutable to the ignore_for_file list

### ISSUE THREAD

**Issue by vr19860507** [google/built_value.dart#813]
When I use linter rule avoid_equals_and_hash_code_on_mutable_classes I have to add @immutable, but if I use  @memoized, then I have this "int __derivedValue;" in the generated file.

**Comment by davidmorgan** [comment]
`built_value` classes are not `@immutable`, as you've discovered. I don't think trying to make them work with the `@immutable` annotation is the right path.

It's possible to be immutable without using `final` everywhere, and it's possible to be mutable while using `final` everywhere, so the checks for `@immutable` are not particularly useful to `built_value`, which is about deep immutability that allows internal caching for performance.

**Comment by zoechi** [comment]
The linter rule could be added to the ignore_for_file list though

**Comment by davidmorgan** [comment]
Yes, but then you would have a class marked `@immutable` that does not actually meet the definition of `@immutable`, which seems unhelpful :D

**Comment by zoechi** [comment]
I don't understand your comment.
I did not suggest to mark it immutable. I meant to ignore the linter rule complaining about hashCode and equals being implemented in a not immutable class

**Comment by davidmorgan** [comment]
Thanks @zoechi! You are entirely right, I misunderstood.

But on the whole I think people using `built_value` can just turn off `avoid_equals_and_hash_code_on_mutable_classes`. The concept of immutability encoded in `@immutable` is different from the one used in `built_value`, so all the lints related to `@immutable` don't really work.

**Comment by zoechi** [comment]
Sadly it's still only possible to exclude a set of files from analyzing completely, which I don't like because issues with generated code do happen.

Disabling the rule completely is IMHO not a good idea because it should remind people who implement these methods in custom classes that they aren't reliable without precautions. That's basically what all linter rules are about.

The alternative is to disable specific rules inside the affected code file.

I don't like that the burden is on package developers, but you already have a set of such rules in the ignore list so I thought it would be easiest and most effective for all if new linter rules that show violations in the generated code are either fixed if it makes sense or ignored. 

I liked the option that was available in build.yaml for some time that allowed to configure such ignores to be added to generated code, but that was also removed again a while after it was added.
