### ISSUE TITLE
constant constructor

### ISSUE THREAD

**Issue by vr19860507** [google/built_value.dart#814]
How can I use constant constructor?
I want to use this litnter rule "prefer_const_constructors_in_immutables"

**Comment by davidmorgan** [comment]
The `@immutable` concept is not compatible with `built_value`.

`@immutable` requires final fields, but does not check if they contain immutable values.

`built_value` is allowed to use non-final fields internally for caching, and encourages use of immutable values in fields. (Without actually trying to fully enforce it).

I recommend using `built_value` without `@immutable`.

As one specific example of this, it doesn't make sense to use `const` with `built_value` classes, because that would prevent any future optimizations to the generated code from using lazy computation.

**Comment by vr19860507** [comment]
I'm understood, thank you.
