### ISSUE TITLE
Clarify subclassing of BuiltValue

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#83]
It's non-trivial (at least for me) to understand how BuiltValue plays with subclasses and polymorphism. Let me give an example:

I have an immutable WorldState. This WorldState contains a stack of Situations, so that the current most specific situation (like "answering question XYZ") is on top, and the most generic (like "life") is on bottom. It's a [pushdown automaton][].

Anywho, I need a `BuiltList<Situation>` for that stack. And the Situations in that list are all _subclasses_ of Situation (because they are quite diverse).

So how do I do this? 

**Option A** is to have Situation a full BuiltValue implementation. That means:

```
part 'situation.g.dart';

abstract class Situation implements Built<Situation, SituationBuilder> {
  // ...
  Situation._();
  factory Situation([updates(SituationBuilder b)]) = _$Situation;
}
```

But that gives me error about "Inconsistent declarations of 'rebuild'" when implementing the subclasses. And I have a feeling that would be just the beginning of my problems.

Note: I don't actually need Situation to be an implementation class. But I'm including it here because I assume for many applications of BuiltValue that will be the case.

**Option B**, which makes more sense to me, is to leave Situation abstract and not to unleash the BuiltValueGenerator on it.

```
abstract class Situation implements Built<Situation, SituationBuilder> {
  // ...
}
```

But I'm not sure how to do it since `Built<Situation, SituationBuilder>` requires some kind of `SituationBuilder`. Do I just add a class for that? Like this?

```
abstract class SituationBuilder
    implements Builder<Situation, SituationBuilder> {
  @virtual
  int id = _assignUniqueId();
  // .. other common fields ..
}
```

When I do that, the subclass (say, `RandomEncounter`) will need to both extend `SituationBuilder` and implement `Builder<RandomEncounter, RandomEncounterBuilder>`:

```
abstract class RandomEncounterBuilder extends SituationBuilder
    implements Builder<RandomEncounter, RandomEncounterBuilder> {
  // ...

  factory RandomEncounterBuilder() = _$RandomEncounterBuilder;
  RandomEncounterBuilder._();
}
```

Is that correct? Is built_value smart enough to pull the `_assignUniqueId()` initialization from `SituationBuilder` to `RandomEncounterBuilder`?

Is there **Option C**? Am I forcing BuiltValue to do something it wasn't meant to solve?

[pushdown automaton]: https://en.wikipedia.org/wiki/Pushdown_automaton

**Comment by davidmorgan** [comment]
Right, Option A won't work. There's anyway no sensible way for one value type to inherit from another -- it doesn't work for equality/hashCode.

The default should be that your interfaces have nothing Built about them:

abstract class Sitatuation {
}

Then your other classes implement it rather than inherit it:

abstract class RandomEncounter implements Situation {
}

This works similarly for builders.

That should take care of the interface part of the problem. The remainder should be about sharing implementation. Ideally, you can do this via mixins -- and so never actually use "extends". (Well, for mixins you'll "extend Object").

If you have any cases that aren't covered by this, let's dig into them :)

**Comment by filiph** [comment]
Thanks for the reply! 

I have some follow-up questions but don't feel obligated to answer.

> abstract class Situation {
> }

I need Situation to implement `Built<.., ..>` for it to be in built_collection, right? Oh wait, maybe I don't. But then the contents of the BuiltCollection<Situation> could be potentially mutable. Oh well. I can live with that but it would be great to know for sure.

I'm starting to work on some refactoring and I'm actually getting away with having `abstract class Situation implements Built<Situation, SituationBuilder>` and then my `SituationBuilder` is just a hollow abstract class. It works so far.

I have to repeat myself with the `int id = _assignUniqueId();` line in every subclass, though. I'm guessing mixin wouldn't work here, but I'll ask just in case. Would this work?

    abstract class SituationBuilder
        implements Builder<Situation, SituationBuilder> {
      int get id;
      // ...
    }
    
    class RandomId {
      int id = _assignUniqueId();
    }
    
    abstract class RandomEncounterBuilder extends Object
        with RandomId
        implements SituationBuilder {
      // The id initialization is pulled from RandomId.
    }

**Comment by davidmorgan** [comment]
Nope, no need for "Built". There's no way to guarantee deep immutability, sadly -- it's only by convention that only immutable things should go in a built_collection/built_value.

Mixins won't work for fields right now because the generation will think the fields are missing altogether and complain. There's an issue open to pull fields from mixins:

https://github.com/google/built_value.dart/issues/22 

What you _can_ do it initialize in the constructor:

`RandomEncounterBuilder {
  @virtual
  int id;

  RandomEncounterBuilder._() {
    id = 7;
  }
}
`

Which is not especially useful as you can't mix in the constructor ... but you could do something like this:

`RandomEncounterBuilder implements HasId {
  @virtual
  id = 7;

  RandomEncounterBuilder._() {
    initWithId(this);
  }
}

void initWithId(HasId hasId) {
  hasId.id = assignUniqueId();
}
`

Not sure if that's an improvement, though :)

**Comment by filiph** [comment]
Thanks!

**Comment by filiph** [comment]
Alright, I remembered why I need `Situation` to be implementing `Build<Situation,SituationBuilder>`. It's because I need to call `rebuild()` on the situations in the stack.

Example:

    situations[index] = situations[index].rebuild(updates);

I can't just put `Situation rebuild(updates(builder));` as an abstract method in `Situation`, because the argument to the `updates` closure is `dynamic` and strong mode (correctly) screams about this.

So back to `abstract class Situation implements Built<Situation, SituationBuilder>`, I guess. If that's a bad idea, please stop me.

**Comment by davidmorgan** [comment]
That should be fine.

If you do run into problems, or if you have cases where it is unnecessarily verbose/awkward -- please do open issues for them. This is an area that built_value should be good at, so if there's anything to improve, let's do it :)

Thanks!

**Comment by Rahuvich** [comment]
I faced the same problem as @filiph, I needed my `abstract User class` to implement `Build<User,UserBuilder>` because I need to call `rebuild()` on the `User`. 
The problem now is, my classes implementing `User` can not implement `Build<X,XBuilder>` at the same time. Two options here: stop implementing `Build<X,XBuilder>`, but then executing `build_runner build` fails, or stop implementing `User`, but then my polymorphism stop working. Any solution on this?

**Comment by davidmorgan** [comment]
A base class can be tagged `@BuiltValue(instantiable: false)`, see examples in

https://github.com/google/built_value.dart/blob/master/example/lib/polymorphism.dart

--does that help?
