### ISSUE TITLE
Discriminator for typed fields?

### ISSUE THREAD

**Issue by CosmicPangolin** [google/built_value.dart#848]
@davidmorgan How much effort is it to provide a  StandardJSONPlugin option `discriminateFields` for typed fields?  This is particularly useful for GraphQL APIs where the query might have a different shape than the model used to save data.  Or does this exist and I'm confused? :)

**Comment by CosmicPangolin** [comment]
I adapted the plugin locally, lmk if you want a PR:

```
  final bool discriminateObjectFields;
  StandardGraphQLJsonPlugin(
      {this.discriminator = r'$',
      this.valueKey = '',
      this.discriminateObjectFields = false});


  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is List &&
        specifiedType.root != BuiltList &&
        specifiedType.root != BuiltSet &&
        specifiedType.root != JsonObject) {
      if (specifiedType.isUnspecified || discriminateObjectFields == true) {
        if (!specifiedType.isUnspecified) {
          object.insert(0, specifiedType.toString());
        }
        return _toMapWithDiscriminator(object);
      } else {
        return _toMap(object, _needsEncodedKeys(specifiedType));
      }
    } else {
      return object;
    }
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Map && specifiedType.root != JsonObject) {
      if (specifiedType.isUnspecified || discriminateObjectFields == true) {
        return _toListUsingDiscriminator(object);
      } else {
        return _toList(object, _needsEncodedKeys(specifiedType));
      }
    } else {
      return object;
    }
  }

```

**Comment by davidmorgan** [comment]
I'm confused--what does this do compared to the existing `discriminator` functionality? Maybe some JSON examples would make it clear :) thanks!

**Comment by CosmicPangolin** [comment]
@davidmorgan - for a value type User that has a field of value type Image: 

StandardJsonPlugin --
`{$: User, firebaseUserId: 1234blablabla, displayName: Blabbidy, email: blabla@blah.com, profilePhoto: {createdTime: 1586818966219506, updatedTime: 1586818966220508, fileName: firebase_profile_photo.jpg }, createdTime: 1586818966224498, updatedTime: 1586818966225793}`

vs.

GraphQLJsonPlugin --
`{$: User, firebaseUserId: 1234blablabla, displayName: Blabbidy, email: blabla@blah.com, profilePhoto: {$: Image, createdTime: 1586818966219506, updatedTime: 1586818966220508, fileName: firebase_profile_photo.jpg }, createdTime: 1586818966224498, updatedTime: `1586818966225793}`

The first serialization works fine if the data is stored and retrieved as a single document.  But in a graph api, the Image is stored as a separate node connected by the predicate profilePhoto.  It can be retrieved in queries that don't include User (eg. query the node directly, or traverse the graph from another direction), and thus needs the discriminator for deserialization.

**Comment by davidmorgan** [comment]
Ah, so this is about whether the discriminator gets written or not?

By default that is determined by whether the enclosing class contains a concrete type or not.

So if for example you made a class called `ImageInterface`, and then `Image implements ImageInterface`, and then the field in `User` is of type `ImageInterface` instead of `Image`, then `built_value` sees that it is an interface type rather than a concrete type, and will write the discriminator.

Rather than an option on the plugin I wonder if this should be an option on `Serializers`. See `built_value/lib/src/built_json_serializers.dart` and in particular the `_serialize` method where it decides whether to look up the serializer using the runtime type or the `specifiedType`. That's probably the right place to have an option to write the type even though it isn't needed.

What do you think?

Thanks.

**Comment by CosmicPangolin** [comment]
Yeah I think that makes sense, my implementation definitely feels hack-y in modifying the list ex-post-facto.
