### ISSUE TITLE
serialize 3rd-party package?

### ISSUE THREAD

**Issue by 2x2xplz** [google/built_value.dart#867]
sorry if this is already covered somewhere, was unable to find it

Is it possible to generate serializers for objects from my `pub.dev` dependencies or other third-party packages? I tried `extend`ing and `implements` and `mixin` but no luck, finally I just created a new abstract object that implements `Built` with the 3rd-party object as a getter. It built ok but at runtime threw `Unhandled Exception: Bad state: No serializer for 'Uuid'` (replace `Uuid` with any 3rd party package).

Thank you.

**Comment by davidmorgan** [comment]
No, there's no way to generate serializers for classes that do not already implement `Built`.

You can hand code serializers, see e.g. https://github.com/google/built_value.dart/blob/master/built_value/lib/src/duration_serializer.dart and https://github.com/google/built_value.dart/blob/master/built_value/lib/src/built_list_serializer.dart for examples of built-in serializers that are hand coded instead of generated.

**Comment by 2x2xplz** [comment]
Thx for the quick reply
