### ISSUE TITLE
StandardJsonSerializer: serialize BuiltValue class as its single string field.

### ISSUE THREAD

**Issue by GiacomoRandazzo** [google/built_value.dart#873]
Hi,

I've encountered a problem in deserializing the following `Id` class:

```dart
abstract class Id implements Built<Id, IdBuilder> {
    String get value;

    // for convenience
    factory Id([String value]) =>
      _$Id((b) => value != null ? (b..value = value) : b);

    ...
}
```

I have a custom serializer so that - let's say `value` is `id1` - the `Id` class is serialized as `id1` and not `{value: id1}`.

Here's the code:

```dart
class IdSerializer implements PrimitiveSerializer<Id> {
  final structured = false;
  @override
  final types = <Type>[Id];
  @override
  final wireName = 'Id';

  @override
  Object serialize(Serializers serializers, Id id,
      {FullType specifiedType = FullType.unspecified}) {
    return id.value;
  }

  @override
  Id deserialize(Serializers serializers, Object serialized,
      {FullType specifiedType = FullType.unspecified}) {
    return Id(serialized as String);
  }
}
```

This works well in most cases, with an exception. Here's were I need your help.
When, in a BuiltValue class, I have a `BuiltMap<Identifier, String> get map` field deserialization stops working (second parameter can be whatever, not necessarily `String`) .
Unless, in the JSON, the map's key is a number (not starting with 0), I get a `FormatException: Unexpected Character` from

https://github.com/google/built_value.dart/blob/c639efb991bad52cb903ade6fd5619a2679c02ef/built_value/lib/standard_json_plugin.dart#L204-L207

I solved the issue by changing

https://github.com/google/built_value.dart/blob/c639efb991bad52cb903ade6fd5619a2679c02ef/built_value/lib/standard_json_plugin.dart#L74-L76

into

```dart
bool _needsEncodedKeys(FullType specifiedType) =>
      specifiedType.root == BuiltMap &&
      specifiedType.parameters[0].root != String &&
      specifiedType.parameters[0].root != Id;
```

I was wondering if this is the intended behavior and if yes, if I'm doing something wrong and there is a cleaner way to solve the problem.

I appreciate your work.

**Comment by davidmorgan** [comment]
Maps are difficult with `StandardJsonPlugin` because JSON keys have to be strings. So, we have to JSON-encode anything that is not a string before using it as a key. For anything that is _already_ a string, we have to know that it is already a string, to avoid an unnecessary json encoding/decoding step that would make the wire format awkward.

This is exactly the `_needsEncodedKeys` method that you found, so your fix is in the right place :)

Unfortunately there isn't a pluggable way to do this right now.

This is the same issue as

https://github.com/google/built_value.dart/issues/494

--the proper fix is to add a new type of serializer, `StringSerializer`, which is a specialized version of `PrimitiveSerializer` that always returns a string. If you use that, we know that we don't have to json encode for keys.

The fix for your issue is actually slightly simpler than for enums, because the fix for enums is a breaking change (changes serialization format) whereas you are adding a custom serializer so it would not be breaking for anyone else.

**Comment by davidmorgan** [comment]
Closing in favour of #494
