### ISSUE TITLE
Polymorphism of more than 1 level

### ISSUE THREAD

**Issue by KeithMarcusXIII** [google/built_value.dart#875]
I've seen the polymorphism example. But given an inheritance as such, Cat -> Mammal -> Animal. Is it possible to use Mammal built value, while `final Mammal mammal = Cat()` & `final Animal animal = Mammal()` are valid?

**Comment by davidmorgan** [comment]
No, it's not possible to have multi levels of `built_value` classes be instantiable.

This is because equality doesn't work with inheritance:

https://stackoverflow.com/questions/12239344/why-should-i-not-use-equals-with-inheritance

and equality is one of the fundamental problems you need for value types.

**Comment by KeithMarcusXIII** [comment]
Thanks for clarifying!
