### ISSUE TITLE
Serializers.deserializeWith<T> should take Object? instead of Object

### ISSUE THREAD

**Issue by jamesderlin** [google/built_value.dart#964]
TL;DR: `Serializers.deserializeWith<T>`'s requirement for a non-null `Object` argument introduces a change in runtime behavior and means that callers must manually do additional validation for correctness.

----

built_value 8.0.0-nullsafety.0 declares `Serializers.deserializeWith<T>` as:

```dart
T deserializeWith<T>(Serializer<T> serializer, Object serialized);
```

I think that the `serialized` parameter would be better as `Object?` instead of as `Object`.  The non-nullable signature prevents direct use with `json.decode`.  For example, https://medium.com/flutter/some-options-for-deserializing-json-with-flutter-7481325a4450, recommends:

```dart
final myObject = serializers.deserializeWith(
    SimpleObject.serializer, json.decode(aJsonString));
```

`json.decode` returns type `dynamic`, and it's sensible and legal for `json.decode('null')` to return `null`.  People with `implicit-casts: false` will get a (somewhat confusing) analysis error about the type mismatch:

> error • A value of type 'dynamic' can't be assigned to a variable of type 'Object' at ... • (invalid_assignment)

People might attempt to fix the error by using `json.decode(...) as Object` (as weird as that looks), or people who realize that the error is caused by a nullable/non-nullable mismatch might try `json.decode(...)!`.  However, both choices are wrong because both will fail at runtime with a `CastError`, which is different from the `DeserializationError` or `FormatException` failures that existing code expects for malformed or unexpected input.

**Comment by davidmorgan** [comment]
Thanks James.

I agree the different exception type is awkward, but I think this is correct as-in; the serialization format doesn't allow nulls, so it will always throw. Accepting `Object?` then throwing on null makes it a runtime error that could have been flagged up statically. Getting `CastError` in these cases seems like a standard part of using null safety.

There's a more awkward question about whether it _should_ allow nulls. In `built_value` 7 there was an option to allow nulls, but I removed this for 8 because it doesn't fit well with null safety. But, `json.decode` already doesn't fit well with null safety, because it returns collections that might contain null. I guess that's a more general question--could we have a json decode that throws on null? That should be more efficient on the VM, I guess it isn't possible on web. (Or rather, it would be a post-decode step that doesn't add much).

**Comment by jamesderlin** [comment]
> Accepting `Object?` then throwing on null makes it a runtime error that could have been flagged up statically.

I disagree.  Typically the JSON-encoded string comes from some potentially untrusted source.  That must *inherently* be checked at runtime.

> Getting `CastError` in these cases seems like a standard part of using null safety.

Since [it's technically wrong for `DeserializationError` to be an `Error` instead of `Exception`](https://github.com/google/built_value.dart/issues/696), I don't think that we should propagate that misuse further by relying `CastError`.  Callers would need to explicitly check whether `json.decode` returns null before calling `deserializeWith` and then explicitly throw `DeserializationError` themselves.  I think is too much of a burden and is too inconsistent/error-prone (constructing a `DeserializationError` is not particularly straightforward).

> could we have a json decode that throws on null?

I believe that the string `'null'` is valid JSON; consequently, I do not think that it would be correct for `json.decode` to reject it.  I think it would be more appropriate for the deserialization step to reject it when attempting to assign `null` to a non-nullable type, **the same way that it would reject other type mismatches** during deserialization.

**Comment by davidmorgan** [comment]
It's the caller that knows whether the JSON comes from an untrusted source; `built_value` doesn't know whether it's a programmer error or a runtime error when it sees null.

It's hard to untangle _validation_ from _processing_ in an efficient and nice way. I don't think the error/exception distinction is up to the job, which is why I don't worry much about maintaining it. Callers should just catch everything, probably at the level of the RPC operation rather than the deserialization itself. I like the advice here: https://www.oracle.com/technical-resources/articles/enterprise-architecture/effective-exceptions-part2.html

The main reason I went for handling nulls early is pragmatic, it reduces the amount of generated code, because code that can assume no nulls is now shorter than code that has to deal with nulls.

**Comment by jamesderlin** [comment]
> It's the caller that knows whether the JSON comes from an untrusted source; `built_value` doesn't know whether it's a programmer error or a runtime error when it sees null.

1. Well, I guess I have a stance that since the purpose of serialization/deserialization is to export/import data and that once the data has left the application, it should always be considered untrusted.  Even if a client is communicating with what is presumed to be a trusted server, I still think that the client should be wary of what comes from the server and that it shouldn't crash if it receives an unexpected response.
2. Why should a null-mismatch be treated differently from any other type mismatch during deserialization?

> Callers should just catch everything, probably at the level of the RPC operation rather than the deserialization itself.

A blanket `catch (e)` also goes against the Effective Dart guidelines.  While I think catching all `Exception`s might be reasonable, requiring everyone to catch all `Error` seems extreme.

> The main reason I went for handling nulls early is pragmatic, it reduces the amount of generated code, because code that can assume no nulls is now shorter than code that has to deal with nulls.

Why can you assume anything about the incoming JSON string?  The whole reason why I use `built_value` for JSON serialization/deserialization instead of doing it manually is so that it automatically handle all of the edge cases of invalid input.

**Comment by davidmorgan** [comment]
> > It's the caller that knows whether the JSON comes from an untrusted source; `built_value` doesn't know whether it's a programmer error or a runtime error when it sees null.
> 
> 1. Well, I guess I have a stance that since the purpose of serialization/deserialization is to export/import data and that once the data has left the application, it should always be considered untrusted.  Even if a client is communicating with what is presumed to be a trusted server, I still think that the client should be wary of what comes from the server and that it shouldn't crash if it receives an unexpected response.

That's up to the application, not the library.

Any time an application passes untrusted data to any library, the application is responsible for catching anything the library throws. Otherwise, a bug in the library could be exploitable.

> 2. Why should a null-mismatch be treated differently from any other type mismatch during deserialization?

The static type should be as tight as it can be; if the serialization format only allowed maps, we would write that, and not `Object`. This is then more efficient if you are deserializing something in a context where you know it's a map.

Note that `built_value` doesn't actually handle JSON. It handles primitive collections that happen to correspond easily to JSON. But that mapping to strings was always outside `built_value`. This could give a `FormatException`.

Looking at existing error handling code in google3, it is almost all wrong. It catches `DeserializationError` but not `FormatException`, meaning incorrectly formatted json hits a different codepath. Null will also now hit a different codepath, but this is not a new bug, it's a slightly wider case of the same bug.

> > Callers should just catch everything, probably at the level of the RPC operation rather than the deserialization itself.
> 
> A blanket `catch (e)` also goes against the Effective Dart guidelines. While I think catching all `Exception`s might be reasonable, requiring everyone to catch all `Error` seems extreme.

I don't think Effective Dart fully addresses the problems around error handling.

When handling untrusted data, there _must_ be a codepath that handles unexpected throws. Otherwise, it's vulnerable to exploits. If it happens that this codepath already works for _expected_ throws, as is likely the case for serialization, then you don't need two codepaths.

The code in google3 currently _accidentally_ has two codepaths, with various potential nasty side effects. It would be more correct, more future proof and simpler to just catch everything.

> 
> > The main reason I went for handling nulls early is pragmatic, it reduces the amount of generated code, because code that can assume no nulls is now shorter than code that has to deal with nulls.
> 
> Why can you assume anything about the incoming JSON string? The whole reason why I use `built_value` for JSON serialization/deserialization instead of doing it manually is so that it automatically handle all of the edge cases of invalid input.

But it doesn't, because of `FormatException`. `built_value` doesn't even see if that gets thrown.

I've avoided adding a dependency from `built_value` onto the json encoder/decoder; but this is probably safe enough since it's in the SDK. One route would be to add a utility method that includes the JSON encoding/decoding, catches all errors/exceptions and turns them into one guaranteed type.

**Comment by jamesderlin** [comment]
> The static type should be as tight as it can be; if the serialization format only allowed maps, we would write that, and not `Object`. This is then more efficient if you are deserializing something in a context where you know it's a map.

Sure, but `Serializers.deserializeWith<T>` doesn't know that, so it must take an `Object` and not `Map`.  Again: why is this different for null? `Serailizers.deserializeWith<T>` doesn't know that null should necessarily be disallowed.  is `deserializeWith<SomeClass?>` necessarily wrong?

> Looking at existing error handling code in google3, it is almost all wrong. It catches `DeserializationError` but not `FormatException`, meaning incorrectly formatted json hits a different codepath. Null will also now hit a different codepath, but this is not a new bug, it's a slightly wider case of the same bug.

Well it's a new code path to handle for *my* google3 code since I already did handle both `FormatException` and `DeserializationError`. =P

I agree that `deserializeWith` usage was already non-ideal and error-prone before the null-safety changes, but the addition of a new failure path makes it even worse.  If nothing else, the use of `Object` instead of `Object?` can generate confusing analysis errors about conversion from `dynamic` to `Object` (which is how I became aware of this in the first place).

A helper function to make it simpler would be great, especially since the case I'm complaining about is specifically about a top-level `'null'` string anyway.

**Comment by davidmorgan** [comment]
> > The static type should be as tight as it can be; if the serialization format only allowed maps, we would write that, and not `Object`. This is then more efficient if you are deserializing something in a context where you know it's a map.
> 
> Sure, but `Serializers.deserializeWith<T>` doesn't know that, so it must take an `Object` and not `Map`. Again: why is this different for null? `Serializers.deserializeWith<T>` doesn't know that null should necessarily be disallowed. Should `deserializeWith<SomeClass?>(serializer, null)` necessarily be wrong?

Nulls were always handled specially: null fields are omitted from the serialized format rather than being written. This makes adding and removing nullable fields transparent to the serialized data. As a side effect of this, serializers never need to accept null and should not return null.

The null safe API just makes this explicit :)

> 
> > Looking at existing error handling code in google3, it is almost all wrong. It catches `DeserializationError` but not `FormatException`, meaning incorrectly formatted json hits a different codepath. Null will also now hit a different codepath, but this is not a new bug, it's a slightly wider case of the same bug.
> 
> Well it's a new code path to handle for _my_ google3 code since I already did handle both `FormatException` and `DeserializationError`. =P

:)

> 
> I agree that `deserializeWith` usage was already non-ideal and error-prone before the null-safety changes, but the addition of a new failure path makes it even worse. If nothing else, the use of `Object` instead of `Object?` can generate confusing analysis errors about conversion from `dynamic` to `Object` (which is how I became aware of this in the first place).

`dynamic` is an unfortunate corner for null safety :/
 
> A helper function to make it simpler would be great, especially since the case I'm complaining about is specifically about a top-level `'null'` string anyway.

SGTM, I'll try to get to that in the next week or so, likely we need a minor release for other reasons anyway.

Thanks.

**Comment by jamesderlin** [comment]
I finally looked at #980, but I don't think it addresses this.  The motivation for a `fromJson` helper function was to throw a `DeserializationError` if given a JSON string of `"null"` so that callers wouldn't have to catch an extra `CastError` type.

**Comment by dave26199** [comment]
Related, I need to fix: https://github.com/google/built_value.dart/issues/984

**Comment by binajmen** [comment]
As a newcomer to Flutter, I'm facing the below issue that seems related to the above topic (or not?).

```A value of type 'Place?' can't be returned from the method 'fromJson' because it has a return type of 'Place'```

```dart
import 'dart:convert';

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:sitback/models/serializers.dart';

part 'place.g.dart';

abstract class Place implements Built<Place, PlaceBuilder> {
  String? get id;
  String get name;
  String get address;
  bool get open;
  BuiltList<String> get methods;

  Place._();

  factory Place([void Function(PlaceBuilder) updates]) = _$Place;

  String toJson() {
    return json.encode(serializers.serializeWith(Place.serializer, this));
  }

  static Place fromJson(String jsonString) {
    return serializers.deserializeWith(
        Place.serializer, json.decode(jsonString));
  }

  static Serializer<Place> get serializer => _$placeSerializer;
}
```

I could make the return type nullable (`Place?`), but is it the right way? Is the fix you will work on will tackle this situation?

**Comment by dave26199** [comment]
If you expect there will always be a value, add a ! to turn Place? into
Place. It does a null check and will throw if null is found.

Sorry for brief response, posting from phone :)

**Comment by binajmen** [comment]
> If you expect there will always be a value, add a ! to turn Place? into Place. It does a null check and will throw if null is found.

I based myself on tutorials where they don't return a nullable type. Perhaps it was prior to the null-safety thing so they were not bothered by this error?

I don't necessarily expect this to be always true. I suppose I can handle the exception when invoking `fromJson` in a try-catch block (if I understood correctly your propositon).

> Sorry for brief response, posting from phone :)

No prob, I'm thankful that you took the time to respond by phone ;) I'll go with your solution for the time being. Do not hesitate to correct me if I misunderstood something :)

**Comment by anqit** [comment]
I'm running in to this as well. I think it would be great if documentation could be updated to express what the ideal pattern for handling the `A value of type '<class>?' can't be returned from the method 'fromJson' because it has a return type of '<class>'` error. As it is, any given examples that I've been able to find don't compile anymore.
